export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="af-magic"

plugins=(git)

source $ZSH/oh-my-zsh.sh

export TERM=xterm-256color
export COLORTERM=truecolor

export EDITOR=nvim

alias vim="nvim"
alias lg="lazygit"
alias gs="git status"
alias gd="git diff"

export PATH="$PATH:$HOME/.scripts"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

bindkey -s ^f "tmux-sessionizer\n"
